name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy Sphinx to GH Pages
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        
      - name: Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Build de la version finale (avec venv isolé)
        run: |
          pip install uv
          
          # 1. Création de l'environnement virtuel
          uv venv
          
          # 2. Activation de l'environnement
          source .venv/bin/activate
          
          # 3. Installation SANS le flag --system
          uv pip install sphinx sphinx-rtd-theme myst-parser
          
          # 4. Compilation
          cd docs
          make html
          
      - name: Déploiement GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html